global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using DexUno.Modern.Core.DataAccess;
global using DexUno.Modern.Core.Entities;
global using DexUno.Modern.Core.Repositories;
global using DexUno.Modern.Core.Services;
global using DexUno.Modern.Presentation;
global using DexUno.Modern.Services;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using Uno.Extensions.Reactive;
