global using System.Collections.Immutable;
global using Dexter.Core.DataAccess;
global using Dexter.Core.Entities;
global using Dexter.Core.Repositories;
global using Dexter.Core.Services;
global using Dexter.Presentation;
global using Dexter.Services;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Uno.Extensions.Reactive;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
